doc
ELiHimself/cafe01-town-hall-new pull request #32
Opened 2022-07-12 17:58 UTC by Wiolla55525

2022-07-12 18:14 UTC, ELiHimself requested changes
link script!

2022-07-13 16:27 UTC, jpsk commented on studentai/violetaVinogrodska/lesson-1/exercise-2/script.js
> +console.log
huh?

2022-07-13 16:27 UTC, jpsk requested changes
one comment below

2022-07-20 15:56 UTC, jpsk requested changes

2022-07-20 15:56 UTC, jpsk commented on studentai/violetaVinogrodska/lesson-2/class-exercises/6-formText.js
> +console.log(formText["Hello world", 3]);
Neteisingai kvieti funkciją. Funkciją kviečiam su paprastais skliaustais, ne su laužtiniais

2022-07-20 15:56 UTC, jpsk commented on studentai/violetaVinogrodska/lesson-2/class-exercises/3-funkcijaMin.js
> +console.log(getMin([5, 6]));
galvok paprasčiau: "jeigu a > b  -> a, kitu atveju -> b."
return a > b ? a : b

2022-07-20 16:18 UTC, Wiolla55525 commented on studentai/violetaVinogrodska/lesson-2/class-exercises/3-funkcijaMin.js
> +console.log(getMin([5, 6]));
pataisyta

2022-07-20 16:18 UTC, Wiolla55525 commented on studentai/violetaVinogrodska/lesson-2/class-exercises/6-formText.js
> +console.log(formText["Hello world", 3]);
pataisyta

2022-07-27 18:33 UTC, closed without merging