branch fix
ELiHimself/cafe01-town-hall-new pull request #40
Opened 2022-07-13 15:34 UTC by mrtfe

new branch + 9/20 javascripting done

2022-07-14 14:58 UTC, jpsk requested changes

2022-07-14 14:58 UTC, jpsk commented on studentai/martynasFetingis/lesson-1/exercise-1-javascript/script.js
> +  };
atitraukimas

2022-07-14 14:58 UTC, jpsk commented on studentai/martynasFetingis/lesson-1/exercise-2-javascripting/javascripting/function.js
> +console.log(eat("bananas "));
tikėtina, kad vartotojas suves be tarpelio žodį, tai geriau perkelt tarpelį į funkciją

2022-07-14 16:39 UTC, mrtfe commented
resolved

2022-07-14 19:03 UTC, mrtfe commented
Please merge to main.

2022-07-20 16:02 UTC, jpsk requested changes

2022-07-20 16:13 UTC, jpsk approved these changes

2022-07-20 16:13 UTC, merged