Mantas pauza
ELiHimself/cafe01-town-hall-new pull request #55
Opened 2022-07-14 16:26 UTC by MantasPauza

class-exercises

2022-07-14 16:37 UTC, jpsk requested changes

2022-07-14 16:37 UTC, jpsk commented on studentai/mantasPauza/lesson-2/class-exercises/math-action.js
> +            return confirm('Error');
pabandyk panaudot ```throw new Error('Klaida');```

2022-07-14 16:37 UTC, jpsk commented on studentai/mantasPauza/lesson-2/exercise-functions/script.js
> +void function () {
void function yra tiesiog paprasčiausia funkcija, kuri nieko negrąžina. direktyva void čia nereikalinga. o jei nori naudoti anonimine funkciją, ir ją iškart pakviesti, naudok IIFE ```(function(){ ...})()```

2022-07-20 15:38 UTC, MantasPauza commented
All requested changes are done

2022-07-20 15:46 UTC, jpsk approved these changes

2022-07-20 15:46 UTC, merged